force-app/main/default/objects/Job_Sequence_Error__c/Job_Sequence_Error__c.object-meta.xml
<CustomObject>
    <description>This object will contain any errors that happened during a batch run</description>
    <label>Job Sequence Error</label>
    <nameField>
        <displayFormat>JSE{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Job Sequence Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Sequence Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sequence_Job__mdt/Sequence_Job__mdt.object-meta.xml
<CustomObject>
    <description>This object contains the various sequences necessary for interval based jobs.</description>
    <label>Sequence Job</label>
    <pluralLabel>Sequence Jobs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Sequence_Job__mdt/fields/AllOrNone__c.field-meta.xml
<CustomField>
    <fullName>AllOrNone__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Should all or none be enforced?</inlineHelpText>
    <label>All or None</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sequence_Job__mdt/fields/BatchLimit__c.field-meta.xml
<CustomField>
    <fullName>BatchLimit__c</fullName>
    <defaultValue>200</defaultValue>
    <inlineHelpText>What should the batch size be set to? You may only enter upto 200</inlineHelpText>
    <label>Job Batch Limit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sequence_Job__mdt/fields/ExecutionJob__c.field-meta.xml
<CustomField>
    <fullName>ExecutionJob__c</fullName>
    <defaultValue>&#39;UPDATE&#39;</defaultValue>
    <inlineHelpText>If the type selected was DML, this should be update or delete. Otherwise it should be the name of the function defined in the UtilityJobSequence class.</inlineHelpText>
    <label>Job Execution DML Type or Function Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sequence_Job__mdt/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <inlineHelpText>How often will this sequence be run?</inlineHelpText>
    <label>Job Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
                <default>true</default>
                <label>Daily</label>
            </value>
            <value>
                <fullName>Hourly</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Test Only</fullName>
            </value>
            <value>
                <fullName>One Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sequence_Job__mdt/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <defaultValue>&#39;SOBJECT_API_NAME&#39;</defaultValue>
    <inlineHelpText>What is the object that will be queried against? DO NOT include the FROM keyword</inlineHelpText>
    <label>Query - From</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sequence_Job__mdt/fields/HandlerClass__c.field-meta.xml
<CustomField>
    <fullName>HandlerClass__c</fullName>
    <defaultValue>&quot;JobSequenceDefaultHandler&quot;</defaultValue>
    <description>The default handler included with the package has some basic functions. See the documentation for more information on how to implement your own handler class.</description>
    <inlineHelpText>If you wish to use a customized handler for your sequence logic, then you must define it here.</inlineHelpText>
    <label>Handler Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sequence_Job__mdt/fields/IsBatchJob__c.field-meta.xml
<CustomField>
    <fullName>IsBatchJob__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Should this be run in a batch context?</inlineHelpText>
    <label>Batch Job</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sequence_Job__mdt/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <inlineHelpText>How many rows should the query be limited to? DO NOT include the LIMIT keyword.</inlineHelpText>
    <label>Query - Record Limit</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sequence_Job__mdt/fields/NotificationEmail__c.field-meta.xml
<CustomField>
    <fullName>NotificationEmail__c</fullName>
    <inlineHelpText>What is the email address that should be used in case of job failure?</inlineHelpText>
    <label>Job Notification Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Sequence_Job__mdt/fields/OrderBy__c.field-meta.xml
<CustomField>
    <fullName>OrderBy__c</fullName>
    <defaultValue>&#39;CreatedDate DESC&#39;</defaultValue>
    <inlineHelpText>What field(s) should the query be ordered by? DO NOT include the ORDER BY keyword; however, you will need to include DESC or ASC as applicable</inlineHelpText>
    <label>Query - OrderBy</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sequence_Job__mdt/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <inlineHelpText>If there are parameters that need to be set to run the function, enter them here. The parameters should be &quot;Parameter Name:Value&quot;. If there are multiple use a comma to separate. e.g. paramName1:value1,paramName2:value2</inlineHelpText>
    <label>Job Parameters</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Sequence_Job__mdt/fields/PermDelete__c.field-meta.xml
<CustomField>
    <fullName>PermDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this is a delete operation, will the deleted records be removed from the recycle bin?</inlineHelpText>
    <label>Permanent Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sequence_Job__mdt/fields/Select__c.field-meta.xml
<CustomField>
    <fullName>Select__c</fullName>
    <defaultValue>&#39;Id&#39;</defaultValue>
    <inlineHelpText>What is the select statement you would like to use? DO NOT include the &#39;SELECT&#39; keyword</inlineHelpText>
    <label>Query - Select</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Sequence_Job__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>When the job is executed, will it be a DML (Database Markup Language, e.g. a simple update statement) or function (a custom function for more advanced functionality, e.g. triggering a field within the record set)?</inlineHelpText>
    <label>Job Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DML</fullName>
                <default>true</default>
                <label>DML</label>
            </value>
            <value>
                <fullName>Function</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sequence_Job__mdt/fields/UpsertExtIdField__c.field-meta.xml
<CustomField>
    <fullName>UpsertExtIdField__c</fullName>
    <inlineHelpText>If this is an upsert operation, this should be the API name of the external Id that will be used to upsert against (if any). Salesforce automatically treats the Id field as the default and should not be defined here if that&#39;s the one to be used.</inlineHelpText>
    <label>Upsert External Id Field</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sequence_Job__mdt/fields/Where__c.field-meta.xml
<CustomField>
    <fullName>Where__c</fullName>
    <defaultValue>&#39;Id &lt;&gt; null&#39;</defaultValue>
    <inlineHelpText>What are the conditions that will be used to filter the result set? DO NOT include the WHERE keyword</inlineHelpText>
    <label>Query - Where</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Sequence_Jobs_Settings__c/Sequence_Jobs_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting provides you with the ability to switch the default settings for the Sequence Jobs</description>
    <label>Sequence Jobs Settings</label>
</CustomObject>

force-app/main/default/objects/Sequence_Jobs_Settings__c/fields/MaxRetries__c.field-meta.xml
<CustomField>
    <fullName>MaxRetries__c</fullName>
    <defaultValue>10</defaultValue>
    <description>This is used to control how many times one job is retried due to there not being enough batch jobs available</description>
    <inlineHelpText>How many times should a job be scheduled to be retried.</inlineHelpText>
    <label>Max Retries</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sequence_Jobs_Settings__c/fields/MinutesUntilRetry__c.field-meta.xml
<CustomField>
    <fullName>MinutesUntilRetry__c</fullName>
    <defaultValue>5</defaultValue>
    <description>If a job is unable to execute, the system will use the number defined here to schedule another try in that many minutes</description>
    <inlineHelpText>How many minutes should elapse between retry attempts?</inlineHelpText>
    <label>Minutes Until Retry</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/JobSequence.cls
/**
 * Copyright 2019 Jason Hardy
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * ----------------------------------------------------------------------------------------
 *
 * This is the a wrapper class which is used by the various job sequence management class to exchange a job. Additionally,
 * contains various functions to manage aspects of a particular job sequence.
 */
global without sharing class JobSequence {
    global Boolean allOrNone {
        get {
            if (this.allOrNone == null) this.allOrNone = true;
            return this.allOrNone;
        }
        set;
    }
    global Boolean isBatchJob {
        get {
            if (this.isBatchJob == null) this.isBatchJob = false;
            return this.isBatchJob;
        }
        set;
    }
    global Boolean permDelete {
        get {
            if (this.permDelete == null) this.permDelete = false;
            return this.permDelete;
        }
        set;
    }
    //This property is used primarily when a date time variable needs to be used to query against if it's specific
    //has to be hard wired like this because of the way that dynamic queries work.
    private Datetime g_DateTimeVar {get;set;}

    global Id jobId {get;set;}

    global String currentJob {get;set;}
    global String executionJob {get;set;}
    global String handlerName { //The name of the handler class that will be run. If none, we'll use the default
        get {
            if (this.handlerName == null) this.handlerName = 'JobSequenceDefaultHandler';
            return this.handlerName;
        }
        set;
    }
    global String jobFrequency {get;set;}
    global String jobType {get;set;}
    public String query {get;set;}
    global String upsertField {get;set;}

    global Integer batchSize {
        get {
            if (this.batchSize == null) this.batchSize = 200;
            return this.batchSize;
        }
        set;
    }
    global Integer numRetries {
        get {
            if (this.numRetries == null) this.numRetries = 0;
            return this.numRetries;
        }
        set;
    }

    global Map<String,String> paramStringsByStrings {get;set;}

    global Sequence_Job__mdt sj {get;set;} //The current sequence job record

    global Sequence_Jobs_Settings__c sjcs { //The sequence job settings, used to check the state of the custom setting
        get {
            this.sjcs = this.sjcs == null ? Sequence_Jobs_Settings__c.getInstance() : this.sjcs;
            //If there isn't a sequence job custom setting active in the org, one will be created here. Particularly
            //useful for when unit tests are running, this gives us the chance to get the default settings from the CS
            if (sjcs == null || sjcs.Name == null) {
                this.sjcs = (Sequence_Jobs_Settings__c) Sequence_Jobs_Settings__c.SObjectType.newSObject(null, true);
                this.sjcs.Name = 'default';
                //Not actually upserting here during testing because it can be problematic when running parallel tests
                if (!Test.isRunningTest()) upsert this.sjcs;
            }
            return sjcs;
        }
        set;
    }

    global JobSequence(){}

    /**
     * Job sequence constructor using a sequence job record
     *
     * @param sj    The sequence job record to initialize with
     */
    global JobSequence(Sequence_Job__mdt sj) {
        this.allOrNone = sj.AllOrNone__c;
        this.batchSize = Integer.valueOf(sj.BatchLimit__c);
        this.currentJob = sj.DeveloperName;
        this.executionJob = sj.ExecutionJob__c;
        this.jobFrequency = sj.Frequency__c;
        this.jobType = sj.Type__c;
        this.paramStringsByStrings = getParamsFromSequenceJob(sj);
        this.query = constructQuery(sj);
        this.sj = sj;
        this.permDelete = sj.PermDelete__c;
        this.upsertField = sj.UpsertExtIdField__c;
        this.isBatchJob = sj.IsBatchJob__c;
        if (this.paramStringsByStrings != null && String.isNotBlank(query)) {
            this.query = updateQueryFromParams(this.query, this.paramStringsByStrings);
        }
        this.handlerName = sj.HandlerClass__c;
    }

    /**
     * Method will log an error in the Job Sequence error object
     *
     * @param jobId     The job Id to log against
     * @param e         The exception
     * @param idScope   The ids that failed
     */
    global void logError(Id jobId, Exception e, Set<Id> idScope) {
        JobSequenceUtilities.logError(jobId, this.currentJob, this.jobFrequency, e, idScope);
    }

    /**
     * Will throw a maximum retry limit reached error
     */
    global void maxRetryLimitReachedError() {
        throw new JobSequenceException(
            String.format(
                    Label.Job_Sequence_Max_Retry_Error,
                    new List<String> {
                            String.valueOf(sjcs.MaxRetries__c),
                            this.sj.DeveloperName,
                            this.executionJob
                    }
            )
        );
    }

    /**
     * Will throw a no function found error
     */
    global void noFunctionFoundError() {
        String errorMsg = String.format(
            Label.Job_Sequence_No_Function_Found_Error,
            new List<String>{
                    this.executionJob
            }
        );
        throw new JobSequenceException(errorMsg);
    }

    /**
     * Will throw a no parameters found error
     */
    global void noParametersFoundError() {
        throw new JobSequenceException(
            String.format(
                Label.Job_Sequence_Parameters_Not_Found,
                new List<String> {
                        this.executionJob,
                        this.sj.Id
                }
            )
        );
    }

    /**
     * Function will schedule a future run for the current job sequence
     *
     * @param js    The current job sequence.
     */
    global void scheduleRetry(JobSequence js) {
        if (js.numRetries >= this.sjcs.MaxRetries__c) js.maxRetryLimitReachedError();
        if (js.numRetries <= this.sjcs.MaxRetries__c) {
            js.numRetries++;
            Datetime futureRunTime = Datetime.now().addMinutes(Integer.valueOf(this.sjcs.MinutesUntilRetry__c));
            String timeForScheduler = futureRunTime.format('s m H d M \'?\' yyyy');
            System.schedule(js.currentJob+' Retry:'+timeForScheduler,timeForScheduler,new JobSequenceSchedulable(js,true));
        }
    }

    /**
     * This function will send error emails if applicable
     *
     * @param jobId     The job Id that will be used to identify the job that errored out
     * @param errors    The error message records
     */
    global void sendErrorEmail(Id jobId, List<Job_Sequence_Error__c> errors) {
        sendErrorEmail(jobId,this.currentJob, this.jobFrequency, errors);
    }

    /**
     * Function will structure a query based on the data found in the sequence job record
     *
     * @param sj    The Sequence Job object record
     *
     * @return      The constructed query
     */
    private String constructQuery(Sequence_Job__mdt sj) {
        String returnQuery = 'SELECT {0} FROM {1} WHERE {2} ORDER BY {3}';
        String limitStr = sj.Limit__c != null ? String.valueOf(sj.Limit__c) : null;
        limitStr = String.isNotBlank(limitStr) && limitStr.endsWith('.0') ? limitStr.left(limitStr.length()-2) : limitStr;
        returnQuery += String.isNotBlank(limitStr) ? ' LIMIT '+limitStr : '';
        return String.format(returnQuery,new List<String>{sj.Select__c,sj.From__c,sj.Where__c,sj.OrderBy__c});
    }

    /**
     * Method will get parameters from the sequence job passed
     *
     * @param sj    The Sequence Job object record
     *
     * @return      The parameter map
     */
    private Map<String,String> getParamsFromSequenceJob(Sequence_Job__mdt sj) {
        Map<String,String> returnMap;
        if (String.isNotBlank(sj.Parameters__c)) {
            returnMap = new Map<String,String>();
            List<String> paramList = sj.Parameters__c.replaceAll('(\\r|\\n)+','').trim().split(',');
            for (String params : paramList) {
                List<String> paramPair = params.split(':');
                returnMap.put(JobSequenceUtilities.trimCharacters(paramPair[0].trim().toLowerCase(),'"'),JobSequenceUtilities.trimCharacters(paramPair[1],'"'));
            }
        }
        return returnMap;
    }

    /**
     * This function will send error emails if applicable
     *
     * @param jobId         The job Id that will be used to identify the job that errored out
     * @param currentJob    The name of the current job
     * @param jobFrequency  The frequency of the current job
     * @param errors        The error message records
     */
    private void sendErrorEmail(Id jobId, String currentJob, String jobFrequency, List<Job_Sequence_Error__c> errors) {
        if (errors != null && !errors.isEmpty()) {
            String notificationEmail = this.sj == null ? UserInfo.getUserEmail() : this.sj.NotificationEmail__c;
            List<String> emails = (this.sj == null || String.isBlank(this.sj.NotificationEmail__c)) ?
                    null : new List<String>{notificationEmail};
            JobSequenceUtilities.sendEmailNotification(
                    null,
                    emails,
                    null,
                    UserInfo.getUserId(),
                    String.format(Label.Job_Sequence_Error_Email_Subject,new List<String>{currentJob,jobFrequency}),
                    String.format(Label.Job_Sequence_Error_Email_Body,new List<String>{jobId}),
                    null,
                    'High'
            );

        }
    }

    /**
     * This function will update the date time variable stored at the class level
     *
     * @param paramMap  The map of parameters to be used to to update date time variable
     */
    @TestVisible void updateDateTimeVar(String testingParam, Map<String,String> paramMap) {
        if (paramMap.containsKey(testingParam)) {
            String paramVal = paramMap.get(testingParam);
            if (paramVal.containsIgnoreCase('DateTimeVar')) {
                this.g_DateTimeVar = System.now().addMinutes(Integer.valueOf(paramVal.split('=')[1]));
            }
        }
    }

    /**
     * This function will update the query based on params. This is particularly useful for testing scenarios where
     * we need to swap out values based on whether or not testing is running
     *
     * @param q         The query to update
     * @param paramMap  The parameter map containing the updated value
     *
     * @return          The updated query
     */
    @TestVisible String updateQueryFromParams(String q, Map<String,String> paramMap) {
        String testingParam = Test.isRunningTest() ?
                Label.Job_Sequence_Test_Is_Running_Param : Label.Job_Sequence_Test_Is_Not_Running_Param;
        testingParam = testingParam.toLowerCase();
        //Checking to see if the query has a parameter update that it's looking for
        if (q.contains('{0}')) {
            q = q.contains('\'') ? q.replaceAll('\'','\'\'') : q;
            String testingParamVal = paramMap.containsKey(testingParam) ? paramMap.get(testingParam) : '';
            q = String.isNotBlank(testingParamVal) ? String.format(q, new List<String> {testingParamVal}) : q;
        }
        //Processing date times that are present
        if (q.containsIgnoreCase('DateTimeVar') && !q.contains('{0}')) {
            updateDateTimeVar(testingParam,paramMap);
            if (this.g_DateTimeVar != null) {
                //Replacing the variable name in the where clause with {0} so we can input the date time as a string
                q = q.replaceAll('(?i)\\:\\s*g_dateTimeVar|\\:\\s*dateTimeVar','{0}');
                q = q.contains('\'') ? q.replaceAll('\'','\'\'') : q;
                q = q.contains('{0}') ?
                        String.format(q,new List<String>{this.g_DateTimeVar.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'')}) : q;
            }
        }
        return q;
    }
}